# Generated by Django 4.0.4 on 2022-05-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=40)),
                ('task_description', models.TextField()),
                ('task_duedate', models.DateField()),
                ('task_priority', models.IntegerField()),
            ],
        ),
    ]
