# Generated by Django 4.0.4 on 2022-05-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_duedate',
            new_name='task_due_date',
        ),
    ]
